### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by acidjunk** [DimensionDataResearch/pynso#2]
Thanks for providing an easy way to connect to NSO from python. Is the project still in 'active' development?

**Comment by tonybaloney** [comment]
NSO is a pretty simple API, so it hasn't had any active development for a while, due mainly to lack of demand for additional features. 
Project is still maintained by paid developers :-)

**Comment by acidjunk** [comment]
Cool, will try to contribute a bit in the coming months.
